### ISSUE TITLE
Build hangs

### ISSUE THREAD

**Issue by spajker** [tyrcho/openshift-cartridge-play2#16]
Every time I try deploy a little bigger application I got result as below.

[info] Compiling 12 Scala sources and 20 Java sources to /var/lib/openshift/5437
04ae50044698c9000375/app-root/runtime/repo/target/scala-2.10/classes...
[info] Main Scala API documentation to /var/lib/openshift/543704ae50044698c90003
75/app-root/runtime/repo/target/scala-2.10/api...
[info] Packaging /var/lib/openshift/543704ae50044698c9000375/app-root/runtime/re
po/target/play-1.0-SNAPSHOT-assets.jar ...
[info] Done packaging.
model contains 61 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging /var/lib/openshift/543704ae50044698c9000375/app-root/runtime/re
po/target/scala-2.10/play_2.10-1.0-SNAPSHOT-javadoc.jar ...
[info] Done packaging.
Connection to (..).rhcloud.com closed by remote host.
Connection to (..).rhcloud.com closed.

**Comment by tyrcho** [comment]
It is now possible with the last version to deploy an application both via source code and via distribution zip file. Please see README.md file. Thanks to @fpirola  for the PR !
