### ISSUE TITLE
status function is missing in bin/control

### ISSUE THREAD

**Issue by simonlopez** [tyrcho/openshift-cartridge-play2#17]
status function must be implemented. without it, openshift is not able to get cartridge status and is not able to move app for instance.

**Comment by tyrcho** [comment]
Could you submit a PR for this ? Or at least point to a good implementation of the status function on another cartridge ?

Unfortunately I have little time for this cartridge at the moment, I'm focusing more on Docker, and the OpenShift instances I have access to are a bit unreliable and slow for testing.

**Comment by tyrcho** [comment]
the command status was added with the 02a8c6ac967fdea1e98548a912fbc04b5a166bdb .
Please see README.md file.
