### ISSUE TITLE
Compatibility 2.4

### ISSUE THREAD

**Issue by callicles** [tyrcho/openshift-cartridge-play2#19]
Hey !

I am looking to deploy a play 2.4.x application with openshift. Are you planning on releasing an update soon ?

I can also pull request something but you would have to tell me how you would like to proceed.

**Comment by didlich** [comment]
+1 , also interested in play 2.4.x

**Comment by tyrcho** [comment]
I don't maintain actively this cartridge, but I would gladly accept a pull request for the latest version of play!

**Comment by callicles** [comment]
ok, I will pull request somthing.

**Comment by callicles** [comment]
Sorry, guys, we decided not to go through with this, we did some work on https://github.com/gitlinks/openshift-cartridge-play2 but debugging stuff on openshift online is a pain.
I will delete that project in one week.
